### ISSUE TITLE
Make gradle projects follow naming schema

### ISSUE THREAD

**Issue by fabapp2** [spring-projects/spring-rewrite-commons#57]
## What needs to be done
Adjust names of modules in [gradle project](https://github.com/spring-projects/spring-rewrite-commons/tree/086dbb4001e971da423c68a1c3f1580fedf1711c/spring-rewrite-commons-gradle).

## Why it needs to be done
The naming schema prefix for all projects is `spring-rewrite-commons-` (as of now). 
The submodules in the [gradle project](https://github.com/spring-projects/spring-rewrite-commons/tree/086dbb4001e971da423c68a1c3f1580fedf1711c/spring-rewrite-commons-gradle) do not follow this naming schema.

**Comment by bsmahi** [comment]
@fabapp2 I will work on it

**Comment by bsmahi** [comment]
Hi @fabapp2 
Here is the PR for your reference

https://github.com/spring-projects/spring-rewrite-commons/pull/58

Could you please review and let me know your feedback.

Thanks,
Mahi
