### ISSUE TITLE
Remove dependency to lombok in gradle modules

### ISSUE THREAD

**Issue by fabapp2** [spring-projects/spring-rewrite-commons#69]
The dependency to lombok in all [gradle projects](https://github.com/spring-projects/spring-rewrite-commons/blob/d1ccaadd0f4607259d022fa33bbb00970435edd0/spring-rewrite-commons-gradle/spring-rewrite-commons-rewrite-gradle-plugin) projects should be removed.

**Comment by bsmahi** [comment]
@fabapp2 I will take up this one

**Comment by bsmahi** [comment]
@fabapp2 here is the PR
https://github.com/spring-projects/spring-rewrite-commons/pull/70
Could you please review it

Thanks,
Mahi

**Comment by fabapp2** [comment]
closed by #70
